# Generated by Django 3.1 on 2021-06-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='process1',
            field=models.CharField(default='test', max_length=150, verbose_name='手順1'),
            preserve_default=False,
        ),
    ]
