# Generated by Django 3.1 on 2021-06-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_process1'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='process2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='手順2'),
        ),
    ]
