# Generated by Django 3.1 on 2021-07-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(default='テスト', max_length=20, verbose_name='カテゴリー'),
        ),
    ]
