# Generated by Django 3.1 on 2021-07-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='main_image',
            field=models.ImageField(default='image_init.png', upload_to=''),
        ),
    ]
